#!/bin/sh
# Reference:
#   https://github.com/musescore/MuseScore/blob/master/build/travis/job_macos/install.sh

set -v
set -e

QT_VERSION=${1:-5.12.0}
QT_TARGET_CATALOG=${2:-$PWD}
QT_CI_DOWNLOADER=${QT_CI_DOWNLOADER:-"wget -c -N"}

DOWNLOAD_URL=https://download.qt.io/archive/qt/$(echo ${QT_VERSION} | cut -d "." -f -2)/${QT_VERSION}/qt-opensource-mac-x64-${QT_VERSION}.dmg
INSTALLER=`basename $DOWNLOAD_URL`
INSTALLER_NAME=${INSTALLER%.*}
ENVFILE=${QT_TARGET_CATALOG}/qt-${QT_VERSION}.env
APPFILE=/Volumes/${INSTALLER_NAME}/${INSTALLER_NAME}.app/Contents/MacOS/${INSTALLER_NAME}

echo Downloading Qt
${QT_CI_DOWNLOADER} $DOWNLOAD_URL
hdiutil attach ${INSTALLER} -noverify
ls /Volumes
echo Installing Qt
extract-qt-installer $APPFILE ${QT_TARGET_CATALOG}/Qt
# occasionally extract-qt-installer seems to return a bit early.
# and we get hdiutil: couldn't unmount "disk1" - Resource busy
#hdiutil detach /Volumes/${INSTALLER_NAME}
count=0
until hdiutil detach /Volumes/${INSTALLER_NAME} || [ $count -ge 5 ]
do
  echo "Wait and attempt to detach again"
  count=`expr $count + 1`
  sleep 5
done

echo Create $ENVFILE
cat << EOF > $ENVFILE
export PATH=${QT_TARGET_CATALOG}/Qt/${QT_VERSION}/clang_64/bin:$PATH
EOF
