language : cpp
compiler: gcc
os: linux
dist: trusty

matrix:
  include:
  - before_install:
        - cat /etc/apt/sources.list
        - sudo apt-get update
        - sudo apt-get install --force-yes -qq p7zip openjdk-7-jdk ant lib32z1-dev lib32stdc++6  #lib32* are needed by Android SDK
        - sudo update-alternatives --display java
        - sudo update-alternatives --set java /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
        - sh -e /etc/init.d/xvfb start
    script:
        - ENV_FILE=qt-5.9.5-android-19.env
        - export WORKDIR=$PWD
        - echo $PWD
        - source path.env
        - wget -c https://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
        - extract-qt-installer --list-packages qt-unified-linux-x64-online.run
        - install-qt-5.9.5-android-19
        - cat $ENV_FILE
        - source $ENV_FILE
        - which qmake
        - git clone https://github.com/benlau/quickandroid.git
        - cd quickandroid/examples/quickandroidexample
        - qmake
        - make install INSTALL_ROOT=$WORKDIR/build
        - androiddeployqt --output $WORKDIR/build
  - os: osx
    script: 
      - QT_CI_PACKAGES=qt.qt5.597.clang_64 PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH} install-qt 5.9.7 && source qt-5.9.7.env && qmake -version && test "$(qmake -query QT_VERSION)" = "5.9.7"
  - os: osx
    script: 
      - QT_CI_PACKAGES=qt.qt5.5120.clang_64 PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH} install-qt 5.12.0 && source qt-5.12.0.env && qmake -version && test "$(qmake -query QT_VERSION)" = "5.12.0"
  - script:
    - QT_CI_PACKAGES=qt.56.gcc_64 PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH} install-qt 5.6.0 && source qt-5.6.0.env && qmake -version && test "$(qmake -query QT_VERSION)" = "5.6.0"
  - script:
    - QT_CI_PACKAGES=qt.56.gcc_64 PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH} install-qt 5.6.1 && source qt-5.6.1.env && qmake -version && test "$(qmake -query QT_VERSION)" = "5.6.1"
  - script:
    - QT_CI_PACKAGES=qt.56.gcc_64 PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH} install-qt 5.6.1-1 && source qt-5.6.1-1.env && qmake -version && test "$(qmake -query QT_VERSION)" = "5.6.1"
  - script:
    - QT_CI_PACKAGES=qt.56.gcc_64 PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH} install-qt 5.6.2 && source qt-5.6.2.env && qmake -version && test "$(qmake -query QT_VERSION)" = "5.6.2"
  - script:
    - QT_CI_PACKAGES=qt.563.gcc_64 PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH} install-qt 5.6.3 && source qt-5.6.3.env && qmake -version && test "$(qmake -query QT_VERSION)" = "5.6.3"
  - script:
    - QT_CI_PACKAGES=qt.59.gcc_64 PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH} install-qt 5.9.0 && source qt-5.9.0.env && qmake -version && test "$(qmake -query QT_VERSION)" = "5.9.0"
  - script:
    - QT_CI_PACKAGES=qt.591.gcc_64 PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH} install-qt 5.9.1 && source qt-5.9.1.env && qmake -version && test "$(qmake -query QT_VERSION)" = "5.9.1"
  - script:
    - QT_CI_PACKAGES=qt.592.gcc_64 PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH} install-qt 5.9.2 && source qt-5.9.2.env && qmake -version && test "$(qmake -query QT_VERSION)" = "5.9.2"
  - script:
    - QT_CI_PACKAGES=qt.593.gcc_64 PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH} install-qt 5.9.3 && source qt-5.9.3.env && qmake -version && test "$(qmake -query QT_VERSION)" = "5.9.3"
  - script:
    - QT_CI_PACKAGES=qt.594.gcc_64 PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH} install-qt 5.9.4 && source qt-5.9.4.env && qmake -version && test "$(qmake -query QT_VERSION)" = "5.9.4"
  - script:
    - QT_CI_PACKAGES=qt.595.gcc_64 PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH} install-qt 5.9.5 && source qt-5.9.5.env && qmake -version && test "$(qmake -query QT_VERSION)" = "5.9.5"
  - script:
    - QT_CI_PACKAGES=qt.596.gcc_64 PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH} install-qt 5.9.6 && source qt-5.9.6.env && qmake -version && test "$(qmake -query QT_VERSION)" = "5.9.6"
  - script:
    - QT_CI_PACKAGES=qt.qt5.597.gcc_64 PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH} install-qt 5.9.7 && source qt-5.9.7.env && qmake -version && test "$(qmake -query QT_VERSION)" = "5.9.7"
  - script:
    - QT_CI_PACKAGES=qt.qt5.5120.gcc_64 PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH} install-qt 5.12.0 && source qt-5.12.0.env && qmake -version && test "$(qmake -query QT_VERSION)" = "5.12.0"
